{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekey.postgresql.secretsName" . }}
  labels:
    {{- include "gatekey.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.postgresql.auth.username | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | default (include "gatekey.randomPassword" .) | quote }}
  postgres-db: {{ .Values.postgresql.auth.database | quote }}
{{- end }}
