{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekey.secretsName" . }}
  labels:
    {{- include "gatekey.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  {{- else if .Values.postgresql.enabled }}
  database-url: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password | default (include "gatekey.randomPassword" .) }}@{{ include "gatekey.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable"
  {{- else }}
  database-url: "postgres://{{ .Values.externalDatabase.username }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }}?sslmode=disable"
  {{- end }}
  {{- if .Values.secrets.adminPassword }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
  {{- if .Values.config.auth.oidc.enabled }}
  oidc-client-id: {{ .Values.secrets.oidcClientId | quote }}
  oidc-client-secret: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
{{- end }}
