{{- if or .Values.openvpnGateway.enabled .Values.openvpnHub.enabled .Values.openvpnSpoke.enabled .Values.wireguardGateway.enabled .Values.wireguardHub.enabled .Values.wireguardSpoke.enabled }}
{{- if or (and .Values.openvpnGateway.enabled .Values.openvpnGateway.token (not .Values.openvpnGateway.existingSecret)) (and .Values.openvpnHub.enabled .Values.openvpnHub.token (not .Values.openvpnHub.existingSecret)) (and .Values.openvpnSpoke.enabled .Values.openvpnSpoke.token (not .Values.openvpnSpoke.existingSecret)) (and .Values.wireguardGateway.enabled .Values.wireguardGateway.token (not .Values.wireguardGateway.existingSecret)) (and .Values.wireguardHub.enabled .Values.wireguardHub.token (not .Values.wireguardHub.existingSecret)) (and .Values.wireguardSpoke.enabled .Values.wireguardSpoke.token (not .Values.wireguardSpoke.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatekey.fullname" . }}-vpn-tokens
  labels:
    {{- include "gatekey.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.openvpnGateway.enabled .Values.openvpnGateway.token (not .Values.openvpnGateway.existingSecret) }}
  openvpn-gateway-token: {{ .Values.openvpnGateway.token | b64enc | quote }}
  {{- end }}
  {{- if and .Values.openvpnHub.enabled .Values.openvpnHub.token (not .Values.openvpnHub.existingSecret) }}
  openvpn-hub-token: {{ .Values.openvpnHub.token | b64enc | quote }}
  {{- end }}
  {{- if and .Values.openvpnSpoke.enabled .Values.openvpnSpoke.token (not .Values.openvpnSpoke.existingSecret) }}
  openvpn-spoke-token: {{ .Values.openvpnSpoke.token | b64enc | quote }}
  {{- end }}
  {{- if and .Values.wireguardGateway.enabled .Values.wireguardGateway.token (not .Values.wireguardGateway.existingSecret) }}
  wireguard-gateway-token: {{ .Values.wireguardGateway.token | b64enc | quote }}
  {{- end }}
  {{- if and .Values.wireguardHub.enabled .Values.wireguardHub.token (not .Values.wireguardHub.existingSecret) }}
  wireguard-hub-token: {{ .Values.wireguardHub.token | b64enc | quote }}
  {{- end }}
  {{- if and .Values.wireguardSpoke.enabled .Values.wireguardSpoke.token (not .Values.wireguardSpoke.existingSecret) }}
  wireguard-spoke-token: {{ .Values.wireguardSpoke.token | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
